# Generated by Django 5.2.4 on 2025-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icons/'),
        ),
    ]
