# Generated by Django 5.2.4 on 2025-07-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sedan', 'Sedan'), ('wagon R', 'Wagon R'), ('van', 'Van')], max_length=20)),
                ('capacity', models.IntegerField(help_text='Number of passengers')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDestinationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.destination')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_passengers', models.IntegerField()),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('additional_info', models.TextField(blank=True)),
                ('is_return_trip', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.destination')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicle')),
                ('vehicle_destination_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicledestinationprice')),
            ],
        ),
    ]
