# Generated by Django 5.2.4 on 2025-07-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_destination_description_destination_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
