# Generated by Django 5.2.4 on 2025-07-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
