# Generated by Django 5.2.4 on 2025-07-31 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_destination_alter_booking_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_destination_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicledestinationprice'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='destination_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to='vehicle_images/'),
        ),
    ]
