# Generated by Django 5.1.1 on 2025-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_vehicle_type_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Confirm', 'Confirm'), ('Done', 'Done')], default='Todo', max_length=10),
        ),
    ]
